require 'chapter_one'
require 'chapter_two'
require 'chapter_three'
require 'chapter_four'
require 'chapter_five'
require 'chapter_seven'
require 'chapter_eight'
require 'chapter_nine'
require 'chapter_eleven'
require 'data_structures'

require 'minitest/autorun'
require 'mocha/setup'
