require 'chapter_three/one'
require 'chapter_three/two'
require 'chapter_three/three'
require 'chapter_three/four'
require 'chapter_three/five'
require 'chapter_three/six'
require 'chapter_three/seven'
